apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-express-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-express
  template:
    metadata:
      labels:
        app: ts-express
    spec:
      containers:
      - name: test
        image: razondpro/ts-express-prod
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
