apiVersion: v1
kind: Service
metadata:
  name: ts-express-node-port-srv
spec:
  type: NodePort
  selector:
    app: ts-express
  ports:
    - name: ts-express-node-port
      protocol: TCP
      port: 4000
      targetPort: 3000
